# Generated by Django 4.2.1 on 2023-05-24 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="crimereport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incidenttype", models.CharField(max_length=50)),
                ("date", models.DateField(max_length=20)),
                ("location", models.CharField(max_length=100)),
                ("describe", models.CharField(max_length=8000)),
                ("involvedpeople", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="images")),
                ("role", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=40, unique=True)),
                ("role", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=60)),
                ("phone_number", models.CharField(max_length=10)),
                ("role", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=40)),
                ("userstatus", models.CharField(max_length=20)),
                (
                    "Log_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="police.log"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="policestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=40)),
                ("phone_number", models.CharField(max_length=40)),
                ("role", models.CharField(max_length=10)),
                ("policestatus", models.CharField(max_length=10)),
                (
                    "Log_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="police.log"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="criminalsrecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=60)),
                ("age", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=20)),
                ("dateofbirth", models.CharField(max_length=30)),
                ("hight", models.CharField(max_length=20)),
                ("weight", models.CharField(max_length=20)),
                ("nationality", models.CharField(max_length=60)),
                ("occuption", models.CharField(max_length=60)),
                ("placeofarrest", models.CharField(max_length=40)),
                ("dateofarrest", models.DateField(max_length=20)),
                ("time", models.CharField(max_length=20)),
                ("scarsandmark", models.CharField(max_length=50)),
                ("typeofcrime", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="images")),
                ("role", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=40)),
                (
                    "crimereport_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="police.crimereport",
                    ),
                ),
                (
                    "policestation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="police.policestation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="crimestatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crimename", models.CharField(max_length=40)),
                ("typeofcrime", models.CharField(max_length=50)),
                ("caseupdate", models.CharField(max_length=50)),
                ("casestatus", models.CharField(max_length=100)),
                ("image", models.ImageField(max_length=30, upload_to="")),
                ("locationofcrime", models.CharField(max_length=70)),
                ("caseofdate", models.DateField(max_length=20)),
                ("dateofupdate", models.DateField(max_length=20)),
                ("description", models.CharField(max_length=5000)),
                ("role", models.CharField(max_length=40)),
                ("status", models.CharField(max_length=70)),
                (
                    "crimereport_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="police.crimereport",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crimereport",
            name="userid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="police.user"
            ),
        ),
    ]
