# Generated by Django 4.2.1 on 2023-05-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("police", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crimereport",
            name="role",
        ),
        migrations.RemoveField(
            model_name="crimestatus",
            name="role",
        ),
        migrations.RemoveField(
            model_name="criminalsrecord",
            name="role",
        ),
    ]
