# Generated by Django 4.2.1 on 2023-06-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("police", "0002_remove_crimereport_role_remove_crimestatus_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="criminalsrecord",
            name="crimereport_id",
        ),
    ]
