# Generated by Django 4.2.1 on 2023-06-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("police", "0003_remove_criminalsrecord_crimereport_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("Complaints", models.CharField(max_length=500)),
                ("date", models.DateField(max_length=20)),
                ("replay", models.CharField(default="No replay", max_length=500)),
                ("status", models.CharField(max_length=20)),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="police.user"
                    ),
                ),
            ],
        ),
    ]
